### ISSUE TITLE
Change the `Parser` and `Exporter` API

### ISSUE THREAD

**Issue by mattbrooks2010** [EnableSoftware/DelimitedDataParser#6]
Change the dependencies on `TextReader` and `DataTable` from constructor parameters to method parameters on the `Parse` and `Export` methods. 

This is because the current approach, as constructor parameters, requires calling code to have a `TextReader` and `DataTable` instantiated BEFORE that code is able to configure the options such as `Parser.UseFirstRowAsColumnHeaders` and `Exporter.FieldSeparator`.

It also means a single `Parser` or `Exporter` instance cannot be reused for multiple operations. The current API is the only restriction here — there is potentially no technical restriction.

Finally, it makes mocking and dependency injection difficult.

We should consider releasing this breaking change as v3.0.

**Comment by cgwrench** [comment]
Implemented as 3ce0ad2.
